name: 'ci'
on:
    push:
        branches:
            -   'main'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: pnpm/action-setup@v2.2.1
                with:
                    version: 'latest'
                    run_install: true
            -   name: Set node version to 16
                uses: actions/setup-node@v3
                with:
                    node-version: 'lts/*'
                    cache: 'pnpm'
            -   run: pnpm run test
            -   uses: codecov/codecov-action@v2
                with:
                    fail_ci_if_error: true