name: 'ci'
on:
    push:
        branches:
            -   'main'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: pnpm/action-setup@v2.2.1
                with:
                    version: 'latest'
            -   name: Set node version to latest LTS
                uses: actions/setup-node@v3
                with:
                    node-version: 'lts/*'
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: |
                        ~/cache
                        ~/.pnpm-store
                    key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                    restore-keys: |
                        ${{ runner.os }}-
            -   run: pnpm add node-gyp-cache
            -   run: npm config set node_gyp node-gyp-cache
            -   run: echo node_gyp = node-gyp-cache >> .npmrc
            -   run: pnpm install
            -   run: pnpm run test:ci
            -   uses: codecov/codecov-action@v2
                with:
                    fail_ci_if_error: true