name: 'Release'
on:
    push:
        tags:
            -   'v*'
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: pnpm/action-setup@v2.2.1
                with:
                    version: 'latest'
            -   name: Set node version to latest LTS
                uses: actions/setup-node@v3
                with:
                    node-version: 'lts/*'
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: |
                        ~/cache
                        ~/.cache
                        ~/.pnpm-store
                        ~/.npm
                    key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                    restore-keys: |
                        ${{ runner.os }}-
            -   run: npm install -g node-gyp-cache
            -   run: npm config set node_gyp node-gyp-cache
            -   run: echo node_gyp = node-gyp-cache >> .npmrc
            -   run: pnpm install
            -   run: pnpm run build
            -   name: Publish
                uses: JS-DevTools/npm-publish@v1
                with:
                    access: public
                    token: ${{ secrets.NPM_TOKEN }}
            -   run: zip -r 'conditional_js-${{github.ref_name}}.zip' dist LICENSE package.json README.md
            -   run: tar -czvf 'conditional_js-${{github.ref_name}}.tgz' dist LICENSE package.json README.md
            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        'conditional_js-${{github.ref_name}}.zip'
                        'conditional_js-${{github.ref_name}}.tgz'